### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by shubhi101**
1. Removed background image by grey color fill
2. Changed icons of what, why section
3. Gave proper padding between sections
4. Replaced missing pictures in 'Contributors' section by silhouttes
5. Changed the preferred font to Open-Sans
6. Added hyperlink for wall of thanks

### CODE REVIEW

**Comment by sudheesh001** [comment]
Looks good for a start !
Can we have a json of the games automated with the following fields

```
{
      'name':'Ready Steady Bang',
      'image': 'path of image',
      'link' : 'link to open in the book'
}
```

We can have an array of these objects

**Comment by sudheesh001** [comment]
screen shot 2016-03-21 at 6 10 00 pm

**Comment by shubhi101** [comment]
#1 Fixed now. Please review.

**Comment by shubhi101** [comment]
@sudheesh001 @psurya1994 Please let me know if the PR can be merged now. Working on adding JSON for games automated. Will get back by tomorrow.

**Pull request merged**
